GaijinEntertainment/daScript

- examples/profile/tests/fib.das
Otherwise
```
if (n < 2)
return n
return fibR(n - 1) + fibR(n - 2)
```
looks like
```
if ((err = SSLHashSHA1.update(&hashCtx, &signedParams)) != 0)
goto fail;
goto fail;
```
> fixed identation in fibR (tab -> spaces)

- examples/profile/test_profile.cpp
with gcc 7.4
change tested against clang-8
> make it compile on my ubuntu setup

- include/daScript/simulate/sim_policy.h
- src/builtin/module_builtin_math.cpp
We have fast intrinsics for 1/sqrt and it's estimate version.
> Add builtin rsqrt function

- include/daScript/simulate/aot_builtin_math.h
- src/builtin/module_builtin_math.cpp
Added FLT_MIN, FLT_MAX, FLT_EPSILON
> Add useful constants in math module

- trim_folder_spaces.sh
- trimspaces.bat
- trimspaces.sh
simple utility to trim trailing whitespaces
> trim whitespaces utility

- include/daScript/simulate/simulate.h
- src/simulate/simulate.cpp
flag will be set to true when only one candidate with specified name found.
> add Context::findFunction with 'unique' flag

- site/files/style.css
- site/index.html
The current site breaks on mobile or when zoomed in, and is harder to update because of the table-markup-soup.
These updates modernize it so it works fine in all resolutions and cleans up the html & css a bit.
> Modernize website markup

- include/daScript/simulate/runtime_array.h
- include/daScript/simulate/simulate.h
- include/daScript/simulate/simulate_nodes.h
Fix access for member of generic superclasses
> fix GCC compilation

- site/index.html
- utils/daScript/main.cpp
also fixed extra arguments support for daScript utility
> add vscode extension path/description to main page

- include/daScript/simulate/aot_builtin_debugger.h
- include/daScript/simulate/simulate.h
- src/builtin/module_builtin_debugger.cpp
- src/simulate/simulate.cpp
use correct context in invoke_in_context calls
> rebind get_debug_agent_context, this_context

- src/hal/project_specific_file_info.cpp
additional fix for https://github.com/GaijinEntertainment/daScript/pull/104
> add missing include

- include/daScript/misc/vectypes.h
- include/daScript/simulate/aot_builtin_random.h
- include/daScript/simulate/cast.h
- include/daScript/simulate/sim_policy.h
- include/vecmath/dag_vecMath.h
- include/vecmath/dag_vecMathDecl.h
- include/vecmath/dag_vecMath_common.h
- include/vecmath/dag_vecMath_const.h
- include/vecmath/dag_vecMath_neon.h
- include/vecmath/dag_vecMath_pc_sse.h
- src/simulate/simulate_fusion_op2_scalar_vec.cpp
- src/simulate/simulate_fusion_op2_set_vec.cpp
Internal change-set https://cvs1.gaijin.lan/c/dagor4/+/241862
> rename some internal vecmath API to be less confusing

- include/daScript/daScriptModule.h
> add missing stdint.h header in dasScriptModule.h

- src/modules/uriparser/module_uriparser.cpp
According to documentation https://uriparser.github.io/doc/api/latest/
> fix buffers size passed to uriparser functions

- src/builtin/module_builtin_jobque.cpp
- src/simulate/debug_info.cpp
- utils/dasAot/main.cpp
add Type::fakeLineInfo to g_typeTable to print correct type name
> multiple fixes (get_das_type_name, main function in aot utility, lambda size in threads)

- daslib/debug.das
preview length limit can be configured from launch configurations
"inlinePreviewLimit": 50,
> dap: rework inline preview

- daslib/dap.das
- daslib/debug.das
> dap: very simple evaluate variable support

- daslib/json_boost.das
Reverts GaijinEntertainment/daScript#234
> Revert "correct serialize pointer fields"

- src/builtin/module_builtin_string.cpp
It would be great to add such an overload of the find character index function
> string: finding character index started from some position feature

- site/index.html
Eh I just noticed something wrong with the webpage. Is this a accident or was this intended?
> Safier to safer

- src/builtin/module_builtin_ast_flags.cpp
- src/builtin/module_builtin_rtti.cpp
conflicts with unsafe operator
> rename unsafe flags to _unsafe

- include/daScript/ast/ast.h
The combination of modifyArgument and accessExternal flags is quite common and it would be nice to add it into the flags list
> modifyArgumentAndAccessExternal side effects flag

- include/daScript/simulate/aot_builtin_matrix.h
- src/builtin/module_builtin_math.cpp
There are situations when you need to convert a float3x4 matrix to a float4x4 matrix.
> float4x4_from_float34 binding added

- daslib/das_source_formatter.das
- align multiline function/block arguments
- frework annotion arguments format
- multiple small fixes
> multiple das_source_formatter.das fixes

- include/daScript/simulate/aot.h
- src/builtin/module_builtin_vector_ctor.cpp
also fix potential issues with cvt_float2/4
> fix error: call to 'cvt_float3' is ambiguous

- include/daScript/misc/string_writer.h
miss virtual destructor with virtual class function
> fix VectorAllocationPolicy compile warning

- daslib/strings_boost.das
- tests/strings/strings_distance.das
Levenshtein distance is a string metric for measuring the difference between two sequences
https://en.wikipedia.org/wiki/Levenshtein_distance
> levenshtein distance algorithm

- CMakeLists.txt
- daslib/utf8_utils.das
- doc/reflections/das2rst.das
- examples/test/unit_tests/utf8.das
Useful utilities for conversion to/from UTF-8
utf8_encode - from string/array<uint8> to array of uint (utf-32),
utf8_decode - from array of uint (utf-32) to string/array<uint8>,
utf8_length,
is_utf8_string_valid
> add module utf8_utils.das

- include/daScript/ast/ast_handle.h
- include/daScript/simulate/aot.h
- include/daScript/simulate/aot_builtin.h
- src/builtin/builtin.das
- src/builtin/module_builtin_array.cpp
There are definitely happens situations when you need to remove not just one, but multiple elements of vector or array.
> das vector and array ranged erase added

- include/daScript/simulate/aot.h
- src/builtin/module_builtin_runtime.cpp
useful for auto generated code
> add wrapper ctor to get string from string string(str:string)

- include/daScript/simulate/aot_builtin_matrix.h
> Use v_mat44_make_from_43cu_unsafe for float3x4 math

- include/vecmath/dag_vecMath_pc_sse.h
fix emscripten compile error in web dictionary.
> fix emscripten compile error

- daslib/contracts.das
- examples/test/misc/contracts_example.das
> expect ref/non-ref/pointer

- .github/workflows/build.yml
- src/builtin/module_builtin_network.cpp
Added a GitHub Actions file for a daScript project that allows you to automatically build a project across different systems (linux, windows, macOS) on push and pull requests.
> GitHub Actions for daScript

- .github/workflows/build.yml
- include/daScript/simulate/aot.h
- src/builtin/module_builtin_runtime.cpp
Added daScriptTests build and the "Test" step. Also fixed 1 issue.
> GitHub actions for da script

- .github/workflows/build.yml
Added more tests for GitHub Actions build in daScript project
> More tests for GitHub Actions build

- .github/workflows/build.yml
Added Debug and Release builds for GitHub Actions
> Debug and Release for daScript GitHub Actions

- daslib/ast_boost.das
- daslib/decs_boost.das
- daslib/live.das
- daslib/templates_boost.das
- dastest/dastest.das
- dastest/suite.das
- examples/test/misc/reification.das
- include/daScript/misc/smart_ptr.h
- src/builtin/module_builtin_ast_annotations.cpp
- src/builtin/module_builtin_runtime_lockcheck.cpp
- src/builtin/module_builtin_string.cpp
- tests/decs/test_create_update_remove.das
- utils/daScript/main.cpp
fix bunch of memory leaks in different macros and tests
> Leak memory less

- .github/workflows/build.yml
restore debug configuration for windows ci builds and fixed an issue where Release builds were not actually built for Linux and macOS.
> speedup ci builds and fix 1 issue

- .github/workflows/build.yml
- .github/workflows/wasm_build.yml
1. Added cross-platform emscripten build.
2. CMake is now using Ninja instead of UnixMakefiles on linux and macOS systems
> Wasm GitHub actions

- include/daScript/misc/platform.h
assert and verify now support assertf and verifyf arguments. verify now happens in release builds. we now get file\line clickable link
> remove some tech debt. 

- CustomRules.ruleset
- examples/tutorial/tutorial07.c
- include/daScript/simulate/aot.h
- include/daScript/simulate/sim_policy.h
- include/daScript/simulate/simulate.h
- src/ast/ast_module.cpp
- src/builtin/module_builtin_ast.cpp
- src/builtin/module_builtin_ast_adapters.cpp
- src/builtin/module_builtin_debugger.cpp
- src/builtin/module_builtin_fio.cpp
- src/builtin/module_builtin_jobque.cpp
- src/builtin/module_builtin_runtime.cpp
- src/builtin/module_builtin_string.cpp
- src/builtin/module_jit.cpp
- src/simulate/runtime_string.cpp
- src/simulate/simulate.cpp
- src/simulate/simulate_fn_hash.cpp
- src/simulate/simulate_gc.cpp
fixed massive issue with LineInfo and throw_error_at
> we now display a lot less `bugs` in the analyzer

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/wasm_build.yml
Added MacOS Release build into workflow matrix with the part of the tests. Added action to skip duplicate workflow runs from push and pull requests.
> Skip duplicate workflows and turned on MacOS Release build

- src/parser/ds_lexer.cpp
- src/parser/ds_lexer.lpp
fix invalid number of the error line when error occurs directly on '\n'
> Fix displayed error line

- examples/profile/test_profile.cpp
- include/daScript/misc/memory_model.h
- include/daScript/simulate/aot_builtin.h
- include/daScript/simulate/runtime_table.h
- src/builtin/module_builtin_array.cpp
- src/builtin/module_builtin_fio.cpp
- src/builtin/module_builtin_uriparser.cpp
- src/parser/parser_impl.cpp
- src/simulate/runtime_array.cpp
- src/simulate/simulate_gc.cpp
. size_t(a)*size_t(a) before muliplicaiton is the way, obviously
few other minor bugfixes
> int(a)*int(a) -> size_t is not good

- include/daScript/simulate/aot_builtin_matrix.h
- src/builtin/module_builtin_math.cpp
> neg for matrix

- include/daScript/simulate/interop.h
Now we assert if binding try to return by value
and cast not exist
Now error now tells you what to do to fix it
> static assert: try to return type larger than vec4f

- daslib/curl.das
- daslib/openai.das
- examples/test/misc/openai_wip.das
popen curl for HTTP requests
openai api now uses curl
both are now modules
> openai more wip

- daslib/json.das
- include/daScript/simulate/aot_builtin_string.h
- modules/dasPUGIXML/telegram/godfather_bot.das
- modules/dasPUGIXML/telegram/tbot_log.das
- src/builtin/module_builtin_string.cpp
json now does not crash on numbers without numbers in them functionality which attempts to fix broken json
> better number parsing error reporting

- src/ast/ast_infer_type.cpp
(cherry picked from commit db68b101f24b063f89136311285c810910aa630f)
> with correct dim

- CMakeLists.txt
- modules/dasSQLITE/daslib/sqlite_boost.das
- modules/dasSQLITE/src/aot_sqlite.h
- modules/dasSQLITE/src/dasSQLITE.main.cpp
- modules/dasTelegram/examples/chat_log.das
- modules/dasTelegram/examples/emoji.das
- modules/dasTelegram/examples/godfather_bot.das
- web/CMakeLists.txt
with more unicode and more goo in the bot
> now with passion, and proper set of tutorials

- daslib/archive.das
- tests/archive/test_archive.das
less mem usage for storing strings
linter fixes
> improve archive.das

- daslib/debug.das
also speedup globals collector
> dap: show invisible globals in eval, old simple eval

- daslib/debug_eval.das
- examples/test/misc/test_debug_eval.das
- include/daScript/simulate/aot_builtin_rtti.h
- src/builtin/module_builtin_rtti.cpp
- tests/debug/deval.das
function calls. length. table lookup and table index
> function calls. first function - length

- include/daScript/simulate/aot_builtin.h
- include/daScript/simulate/aot_builtin_rtti.h
- src/ast/ast_allocate_stack.cpp
- src/builtin/module_builtin_runtime.cpp
> we need to check global environment, not particular context

- daslib/debug_eval.das
- src/builtin/module_builtin_rtti.cpp
also fix clang warning in module_builtin_rtti.cpp
> dap: fix linter errors

- src/parser/parser_impl.cpp
```
require math
class Foo
pos : float3
def Foo ( p:float3 )
pos = p
def operator . length
return length(pos)
def operator . length := ( v:float )
pos = normalize(pos) * v
[export]
def main
var f = new Foo(float3(1,2,3))
print("length was = {f.length} // {f}\n")
f.length := 10.
print("length is = {f.length} // {f}\n")
```
> operator methods

- include/daScript/simulate/aot_builtin_raster.h
- src/builtin/module_builtin_raster.cpp
solid color textures with 0 as mask. i know, right!!!
> masked raster

- daslib/raster_boost.das
- src/builtin/module_builtin_runtime.cpp
> with surface data

- src/simulate/simulate_exceptions.cpp
also print exception with stack
> use exception position for stack walk

- include/daScript/misc/memory_model.h
- include/daScript/simulate/debug_info.h
- src/ast/ast_aot_cpp.cpp
- src/ast/ast_debug_info_helper.cpp
- src/simulate/heap.cpp
- src/simulate/simulate_gc.cpp
- faster structs collector
- small fixes and improvements in persistent heap
> gc speedups

- daslib/archive.das
- src/simulate/data_walker.cpp
- src/simulate/simulate_gc.cpp
- Improve and fix HeapReporter
- base gc walker type
> gc speedups (3)

- src/builtin/module_builtin_runtime.cpp
- src/parser/ds_parser.cpp
- src/parser/ds_parser.ypp
- src/simulate/simulate_gc.cpp
> null annotations not crashing

- include/vecmath/dag_vecMath_neon.h
to be able to compile osx release with asan
> NO_ASAN_INLINE for all vldu function for neon version

- include/daScript/simulate/hash.h
- src/builtin/module_builtin_runtime.cpp
- tests/strings/strings_hash.das
useful for generating a hash for a bunch of strings
> fast hash builder without walker and mem allocation

- modules/dasAudio/audio/audio_boost.das
- modules/dasAudio/examples/mixer.das
- modules/dasAudio/src/dasAudio.cpp
- modules/dasAudio/src/volume_mixer.h
not clonning samples extra
deleting cloned commands
> support for basic panning and looping.

- modules/dasAudio/audio/audio_boost.das
- modules/dasAudio/examples/mixer.das
> stream is separated to its own command

- daslib/strings_boost.das
- modules/dasPEG/examples/csv.das
- modules/dasPEG/peg/meta_ast.das
- modules/dasPEG/peg/parse_macro.das
- modules/dasPEG/peg/parser_generator.das
- modules/dasPEG/peg/peg.das
TS rule. Error reporting. Macro no longer rips guts so repeated infer is possible
> CSV: work in progress

- daslib/json.das
- modules/dasPEG/bench/benchmark.das
- modules/dasPEG/examples/csv.das
- modules/dasPEG/examples/declarations.das
- modules/dasPEG/peg/parse_macro.das
- modules/dasPEG/peg/parser_generator.das
- modules/dasPEG/peg/peg.das
- modules/dasPEG/tests/calc.das
- modules/dasPEG/tests/csv.das
- modules/dasPEG/tests/email.das
- modules/dasPEG/tests/json.das
Now parse macro generates the needed boilerplate code itself.
Also there is now several tests that are designed not to parse.
Finally, 2 memoization bugs have shown up in the process of testing.
> Better interface, add failing, fix memoization bugs

- src/builtin/module_builtin_ast_adapters.cpp
Let's check if this doesn't break anything. It should not.
> Provide call factory with module information

- modules/dasAudio/audio/audio_boost.das
- src/builtin/module_builtin_jobque.cpp
because channel requires unsafe delete call
> channel_create is unsafe too

- daslib/templates.das
- include/daScript/ast/ast.h
- src/ast/ast.cpp
Remove unused symbols sometimes deletes the object fromGeneric points to
> Turn fromGeneric into smart pointer

- .github/workflows/build.yml
- daslib/templates.das
- daslib/utf8_utils.das
- dastest/suite.das
- examples/test/main.cpp
- examples/tutorial/tutorial08.cpp
- include/daScript/ast/ast.h
- include/daScript/ast/ast_expressions.h
- include/daScript/ast/ast_serializer.h
- src/ast/ast.cpp
- src/ast/ast_annotations.cpp
- src/ast/ast_const_folding.cpp
- src/ast/ast_export.cpp
- src/ast/ast_module.cpp
- src/ast/ast_parse.cpp
- src/builtin/module_builtin_ast_annotations.cpp
- src/builtin/module_builtin_ast_annotations_3.cpp
- src/builtin/module_builtin_ast_serialize.cpp
- src/builtin/module_builtin_rtti.cpp
- src/builtin/module_builtin_runtime.cpp
- src/parser/parser_impl.h
Let's see if this changes the CI workflow
> Update serialization branch

- src/ast/ast_infer_type.cpp
to write T() for types without default initializer
> less warnings to write generic code

- daslib/debug.das
- src/ast/ast_simulate.cpp
and keep breakOnException if already set
> restore stepping debugger functionality

- examples/pathTracer/path_tracer.cpp
- examples/profile/main.cpp
- examples/test/main.cpp
- examples/test/test_threads.cpp
- examples/tutorial/tutorial02aot.cpp
- include/daScript/ast/ast.h
- src/ast/ast_parse.cpp
- src/builtin/module_builtin_rtti.cpp
- utils/daScript/main.cpp
export_all field already existed, but wasn't used in most cases
> replace exportAll param with policies.export_all

- include/daScript/ast/ast.h
- include/daScript/simulate/aot.h
- src/ast/ast_module.cpp
- src/builtin/module_builtin.cpp
- src/builtin/module_builtin_ast.cpp
- src/builtin/module_builtin_dasbind.cpp
- src/builtin/module_builtin_debugger.cpp
- src/builtin/module_builtin_fio.cpp
- src/builtin/module_builtin_jobque.cpp
- src/builtin/module_builtin_math.cpp
- src/builtin/module_builtin_network.cpp
- src/builtin/module_builtin_raster.cpp
- src/builtin/module_builtin_rtti.cpp
- src/builtin/module_builtin_string.cpp
- src/builtin/module_builtin_uriparser.cpp
- src/builtin/module_jit.cpp
> use addBuiltinDependency

- .gitmodules
point to upstream branch 0.11.18v
3898fff8ed923e118326bf07822961d222cb2a9a
> add miniaudio submodule

- include/daScript/simulate/simulate.h
- src/builtin/module_builtin_debugger.cpp
additional for prev PR
https://github.com/GaijinEntertainment/daScript/pull/782
> fixes found by static analysis

- src/ast/ast_infer_type.cpp
accidentally deleted in prev pr
> restore names collisions check

- modules/dasAudio/src/dasAudio.cpp
- modules/dasAudio/src/dasAudio.h
> force std int types for miniaudio

- src/builtin/module_builtin_runtime_lockcheck.cpp
print type information
print more actual line info
> more informative error in builtin_verify_locks

- include/daScript/simulate/simulate.h
- src/simulate/simulate.cpp
It need for serialization with not null terminated strings
> add intern override with len

- include/daScript/misc/platform.h
to be able to redirect messages
> pass all error messages via DAS_FATAL_LOG

- include/daScript/simulate/aot_builtin_matrix.h
- src/builtin/module_builtin_math.cpp
- tests/math/math_matrix.das
Removed incorrect orthonormal inverse for mat44, added for 3x3 and 3x4
Inline float3x4_det instead of float4x4_det
Small codestyle fixes
> Builtin matrix fixes

- src/builtin/module_builtin_ast_serialize.cpp
- utils/daScript/main.cpp
> update llvm version

- include/daScript/ast/ast.h
- include/daScript/ast/ast_generate.h
- src/ast/ast_generate.cpp
- src/ast/ast_infer_type.cpp
- src/builtin/module_builtin_ast_flags.cpp
- src/builtin/module_builtin_runtime.cpp
> support for no_jit

- src/builtin/module_builtin_ast_annotations_3.cpp
> add necessary pointer casts

- include/daScript/ast/ast_expressions.h
- src/ast/ast_infer_type.cpp
- src/builtin/module_builtin_ast_flags.cpp
- src/simulate/data_walker.cpp
> safe browsing of uninitialized classes

- daslib/json_boost.das
- include/daScript/simulate/aot_builtin_matrix.h
- src/builtin/module_builtin_math.cpp
- tests/json/safe.das
and add quaternion conversion functions for different matrix types
> safe json api

- include/daScript/simulate/simulate_nodes.h
- src/builtin/module_jit.cpp
- src/simulate/simulate.cpp
> and up to date llvm

- include/daScript/ast/ast_serializer.h
- src/builtin/module_builtin_ast_serialize.cpp
bumped on changing new fields and everything
that breaks binary compatibility
> track protocol versions

- daslib/async_boost.das
- examples/test/misc/async_example.das
support `a = await <| async_func()`
support copy, move, clone operators
more validations
> improve async_boost macro

- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_ast.cpp
- src/builtin/module_jit.cpp
- set hashes for functions and bind aot hash
- bind platform's dlopen and dlsym
- add extern "C" for jit_* kind of functions
> add functions for jit dll loading 

- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_ast.cpp
- src/builtin/module_jit.cpp
Reverts GaijinEntertainment/daScript#918
> Revert "add functions for jit dll loading "

- src/builtin/module_builtin_runtime.cpp
- src/simulate/simulate_gc.cpp
> GC is now aware of iterators (2)

- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_ast.cpp
- src/builtin/module_jit.cpp
Reverts GaijinEntertainment/daScript#920
> Revert "Revert "add functions for jit dll loading ""

- generate_msvc_2022.bat
I personally use 2022 mvsc. It's annoying to copy paste bat around
> add mvsc 2022 bat

- daslib/live.das
Export for purpose of dasbox - https://github.com/alohaeee/dasbox/blob/270dd2406118a3eb4c204ddcde4a304cb42d23cc/src/dasbox.cpp#L602
This change need for update dasbox to master daScript
> export set_new_context for dasbox

- src/simulate/simulate_exceptions.cpp
Workaround for https://github.com/google/sanitizers/issues/749 Downstream commit - #453999
> disable ASAN in exceptions code path on Windows

- include/daScript/simulate/aot.h
- include/daScript/simulate/simulate_nodes.h
- include/daScript/simulate/simulate_visit.h
- src/builtin/module_builtin_misc_types.cpp
lexical_cast is a function, not intrinsic
> lexical_cast is a function

- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_debugger.cpp
- tests/language/variants.das
multiple variants in makelocal
> preserve shared stack after runInitScript

- include/daScript/simulate/aot_builtin_math.h
float_control pragma is broken since clang 17.0
> Workaround nan and finite checks on clang 17+

- include/daScript/ast/ast.h
- include/daScript/ast/ast_expressions.h
- include/daScript/ast/ast_serializer.h
- include/daScript/simulate/aot.h
- include/daScript/simulate/aot_builtin_jit.h
- include/daScript/simulate/runtime_table.h
- include/daScript/simulate/simulate.h
- include/daScript/simulate/simulate_nodes.h
- src/ast/ast.cpp
- src/ast/ast_allocate_stack.cpp
- src/ast/ast_aot_cpp.cpp
- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_ast.h
- src/builtin/module_builtin_ast_annotations_2.cpp
- src/builtin/module_builtin_ast_flags.cpp
- src/builtin/module_builtin_ast_serialize.cpp
- src/builtin/module_builtin_runtime.cpp
- src/builtin/module_builtin_string.cpp
- src/builtin/module_jit.cpp
- src/simulate/runtime_string.cpp
- src/simulate/simulate_gc.cpp
- src/simulate/simulate_visit.cpp
print("foo {a} bar {b}") will now que string for release
so will anything else without appropriate side-effect
> WIP: temp string builder

- src/ast/ast_aot_cpp.cpp
to fix warning C5266 issued by vc2022
> aot: avoid using redundunt const on return types 

- daslib/live.das
- include/daScript/simulate/simulate.h
- src/builtin/module_builtin_rtti.cpp
- src/simulate/simulate_exceptions.cpp
to be able to show error without stack
> Add alwaysErrorOnException flag to Context

- examples/pathTracer/toy_path_tracer.das
- include/daScript/misc/job_que.h
- src/builtin/module_builtin_jobque.cpp
- src/misc/job_que.cpp
- src/misc/sysos.cpp
> use all threads

- src/ast/ast_parse.cpp
to figure out what's going on and why it's not working
> log serialization failures

- src/builtin/module_builtin_rtti.cpp
fix set_file_source to accept empty file
> it's ok to have empty das files

- src/ast/ast_generate.cpp
> fix calculated range

- include/daScript/simulate/aot_library.h
- src/ast/ast_aot_cpp.cpp
I wonder if it is possible to make AotFactory a function pointer? In my workspace this change save more than 50% compilation time in some targets with massive functions.
> Make AotFactory as function pointer

- include/daScript/simulate/simulate.h
- src/builtin/module_jit.cpp
- src/simulate/runtime_string.cpp
- src/simulate/simulate.cpp
- src/simulate/simulate_visit.cpp
switching to fmt::format_to on everything
> no more snprintf

- src/ast/ast_infer_type.cpp
to match with ast serialized data
> fix lambda/localfunction names

- daslib/das_source_formatter.das
fixed formatting around '?'
fixed formatting inside types
> formatter: better detection of context

- daslib/match.das
- src/parser/ds_lexer.cpp
- src/parser/ds_lexer.lpp
- src/parser/lex.yy.h
- src/parser/parser_impl.cpp
- src/parser/parser_state.h
type_functions map to keywords 1 to 1
> unify keywords

- daslib/templates_boost.das
1) Allow $t(x) reification with x : Structure?
2) Emit a proper error message when anything else is passed to $t
> $t(...) reification improvements

- examples/test/misc/clone_value_type.das
- examples/test/test_handles.cpp
- examples/test/unitTest.h
- src/ast/ast_simulate.cpp
we also fix some return, move, and clone bugs
> we can clone value types

- src/ast/ast_infer_type.cpp
```
struct Foo
a : int
b : int
def operator . prop:= ( var f : Foo; b : int)
f.a = b
f.b = 0
[export]
def main()
var f = [[Foo prop= 13]] // notice = vs :=
```
> support non-strict properties in make structure

- examples/test/test_handles.cpp
- include/daScript/ast/ast_handle.h
> any managed value can be cloned by default

- include/daScript/ast/ast_serializer.h
- src/ast/ast_parse.cpp
- src/builtin/module_builtin_ast_serialize.cpp
trySerialize method
warnings instead of errors
removed unused metadata
> serialization improvements

- include/daScript/ast/ast.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
- src/ast/ast_parse.cpp
- src/parser/ds_lexer.cpp
- src/parser/ds_lexer.lpp
- src/parser/ds_parser.cpp
- src/parser/ds_parser.ypp
- src/parser/parser_state.h
options gen2_make_syntax
null is no longer const pointer
> its gen2, not new

- examples/test/unit_tests/aotAlias_propagation.das
- src/ast/ast_infer_type.cpp
[this issue](https://github.com/GaijinEntertainment/daScript/issues/1254)
> Fixes compilation of alias propagation, as well as correct type resolving order.

- src/builtin/module_builtin_ast_serialize.cpp
create program only when need it
> speedup deserialization

- src/ast/ast_lint.cpp
- src/ast/ast_parse.cpp
> Good require log

- src/ast/ast_infer_type.cpp
```
enum Foo
One
Two
[export]
def main
var a = Foo.One  // NOTE syntax
print("a={a}\n")
```
> Foo.bar enum syntax

- src/ast/ast_infer_type.cpp
assignment operators like += and such now work on properties
```
struct Foo
n : string
def operator . name
return n
def operator . name := ( v : string )
n = v
[export]
def main
var f : Foo
f.name = "Hello, World!"
print( "f = {f}\n" )
f.name += " (again)" // NOTE += on property
print( "f = {f}\n" )
```
> property operators

- src/builtin/module_builtin_uriparser.cpp
Make it
- always lowercase
- properly formatted
> Fix make_new_guid() implementation

- daslib/decs.das
- daslib/live.das
check stride size before deserializing
> fix crash in decs hot-reload

- include/daScript/simulate/runtime_table.h
Why: we need to have a stack trace there
> Replace throw_error to throw_error_at in table reserve function

- include/daScript/ast/ast.h
- include/daScript/ast/ast_handle.h
- include/daScript/ast/ast_typedecl.h
- include/daScript/misc/anyhash.h
- src/ast/ast_handle.cpp
- src/ast/ast_typedecl.cpp
- src/simulate/simulate_fn_hash.cpp
structures and annotations are now versioned?
> towards better semantic hash

- src/ast/ast_infer_type.cpp
also mark dummy function as generated
> fix `Compilation error: error[30101]: can only dereference a reference`

- include/daScript/ast/ast.h
- src/ast/ast.cpp
- src/ast/ast_aot_cpp.cpp
- src/ast/ast_simulate.cpp
- src/ast/ast_typedecl.cpp
- src/builtin/module_builtin_ast_serialize.cpp
a little less energy on AOT hashes
> caching AOT hash for structures

- include/daScript/ast/ast.h
- src/ast/ast.cpp
- src/ast/ast_aot_cpp.cpp
- src/ast/ast_simulate.cpp
- src/ast/ast_typedecl.cpp
- src/builtin/module_builtin_ast_serialize.cpp
Reverts GaijinEntertainment/daScript#1334
buggy, gonna try some other way
> Revert "caching AOT hash for structures"

- examples/test/misc/hello_world.das
- src/ast/ast_infer_type.cpp
```
def take_mks ( a : Mks ) {
debug(a);
}
def take_mks_and_int ( a : Mks; b : int ) {
debug(a);
debug(b);
}
var mks = Mks();
mks.take_mks();				// method-like call syntax
mks.take_mks_and_int(13);	// method-like call syntax
```
> this can look like method call

- examples/test/misc/hello_new_syntax.das
- include/daScript/ast/ast.h
- include/daScript/ast/ast_expressions.h
- include/daScript/simulate/runtime_array.h
- include/daScript/simulate/runtime_range.h
- include/daScript/simulate/simulate.h
- include/daScript/simulate/simulate_nodes.h
- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_rtti.cpp
- src/simulate/simulate.cpp
- src/simulate/simulate_visit.cpp
DAS_ENABLE_KEEPALIVE is a compilation option, to optimize out code size. but when enabled policies.keep_alive will produce slower code, which keeps things alive
> policies.keep_alive

- include/daScript/ast/ast.h
- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_ast_flags.cpp
> only call keep-alive on recursive-like functions

- src/ast/ast_parse.cpp
setup comments readers before parsing
> fix documentation generator

- src/ast/ast_infer_type.cpp
```
var tab : table<int; int>
tab.clear()
```
> support generics in a.foo(...) semantics

- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
```
let b  = Foo(
a=[1,2,3] // this is also ok under relax assign
)
```
> relax assign in make structure

- src/ast/ast_infer_type.cpp
```
var a = @ <| ( what : string )
print("Hello, {what}!\n")
a("World") // note - invoke(a,"World") is no longer necessary
```
> invoke can now be inferred

- src/ast/ast_infer_type.cpp
```
class Foo
foo : lambda<(a : int) : void>
bar : function<(a : int) : void>
def test()
invoke(foo, 10)
foo(10)
invoke(bar, 10)
bar(10)
```
> direct invoke syntax now works for class or structure fields

- src/ast/ast_infer_type.cpp
```
class Foo
def bar(var f : Foo?; i : int)
debug(f)
debug(i)
[export]
def test()
var fff = new Foo()
fff.bar(1) // this one
```
> fixing more UFCS

- src/ast/ast_infer_type.cpp
- src/ast/ast_typedecl.cpp
also
var a = ... Foo? const -> var a : Foo const? = ... Foo? const
> void pointers are always relaxed constness

- include/daScript/simulate/aot_builtin_matrix.h
- src/builtin/module_builtin_ast_serialize.cpp
also fix euler_from_quat fn name
> update AstSerializer to include new serialization fields and increment version to 40

- include/daScript/ast/ast.h
- include/daScript/simulate/debug_info.h
- src/ast/ast_parse.cpp
> Added parseCustomRequire() to process prerequisites added via reader 

- examples/test/compilation_fail_tests/const_and_block_folding.das
- src/ast/ast_infer_type.cpp
```
[export]
def main()
let x = 5
let X = x + 1
var a : int[X]
debug(a)
```
```
let x = int2(31,2)
let X = x.x + 1
var a : int[X]
debug(a)
```
> folding local constants

- daslib/async_boost.das
to satisfy the const correctness
> async_boost: change parameter to var in preVisitExprBlock method

- include/daScript/ast/ast.h
- include/daScript/simulate/runtime_table.h
- include/daScript/simulate/simulate.h
- src/ast/ast_lint.cpp
- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_rtti.cpp
- src/simulate/runtime_array.cpp
- src/simulate/simulate.cpp
```
options very_safe_context
[export]
def main
var a : array<int>
a |> push(1)
debug(a)
print("capacity = {a.capacity()}\n")
for i in 0 .. a.capacity()
a |> push(i)
debug(a)
print("capacity = {a.capacity()}\n")
var tab <- { 1=>1, 2=>2 }
debug(tab)
print("capacity = {tab.capacity()}\n")
for i in 0 .. tab.capacity()
tab |> insert(i, i)
debug(tab)
print("capacity = {tab.capacity()}\n")
```
> very safe context mode

- src/builtin/module_builtin_runtime.cpp
- src/misc/job_que.cpp
Details:
https://stackoverflow.com/a/73196965
> fix c++20 lambda capture -Wdeprecated-this-capture

- include/daScript/simulate/debug_info.h
- include/daScript/simulate/runtime_array.h
- include/daScript/simulate/runtime_range.h
- include/daScript/simulate/simulate_nodes.h
- src/ast/ast_simulate.cpp
- src/simulate/simulate.cpp
> Undo the damage

- .github/workflows/build.yml
- examples/test/compilation_fail_tests/auto_infer.das
- examples/test/compilation_fail_tests/type_loop.das
Adds formatting (using das_source_formatter) of all das files in repository to CI.
> Add das source formatter for CI

- src/ast/ast_typedecl.cpp
it was not if else, it was just if. so bunch of unnecessary extra checks
> this one a tad touchy

- include/daScript/ast/ast.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_module.cpp
less smart-ptr goo
tiny bit more effective matching lookup
> more optimizations

- src/ast/ast_infer_type.cpp
```
def test_abi_mad ( a,b,c )
print("a={a} b={b} c={c}\n")
return a*b + c
[export]
def main
invoke(@@<(a,b,c:int):int>test_abi_mad, 1, 2, 3) // this will now instance the generic
```
> this fixes address of generic instance

- include/daScript/simulate/aot.h
- include/daScript/simulate/aot_builtin_rtti.h
- src/builtin/module_builtin_rtti.cpp
This will help to remove extra conversions, also we will be able to use this feature in AOT.
> Replace RttiValue struct with variant.

- src/ast/ast_infer_type.cpp
```
error[30101]: Class 'Foo' has fields, which can't be allocated locally, which is not allowed. It contains Handled type, where isLocal() returned false.
D:\Work\daScript/examples/test/misc/hello_world.das:5:5
class Foo {
^^^^
type<Foo>.a : strings::StringBuilderWriter is not a local type
```
> better error message for the local errors

- include/daScript/simulate/aot.h
- include/daScript/simulate/interop.h
- include/daScript/simulate/simulate.h
- include/daScript/simulate/simulate_nodes.h
- src/ast/ast_simulate.cpp
- src/builtin/module_builtin_ast_annotations.cpp
- src/builtin/module_builtin_math.cpp
- src/builtin/module_builtin_rtti.cpp
- src/builtin/module_builtin_vector_ctor.cpp
- src/simulate/simulate.cpp
also up to date modules for version 2 syntax
> more error messages

- src/ast/ast_infer_type.cpp
```
class Foo {
a : int = 1
def test() {
print("test")
}
def main() {
var lmd = @() {
test()
//var b = a   // used to need this to capture self. now works fine
}
lmd()
}
}
```
> delay capture of lambda until calls are resolved, to ensure self is captured properly

- CMakeLists.txt
- examples/pathTracer/CMakeLists.txt
- examples/profile/CMakeLists.txt
- examples/test/CMakeLists.txt
- examples/tutorial/CMakeLists.txt
- web/CMakeLists.txt
Why: to make possible to add daslang as a sub directory in cmake without need Now you need to build that separately or modify dascript cmake
> Replace CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR

- src/simulate/simulate.cpp
Addresses https://github.com/GaijinEntertainment/daScript/issues/1628
> loops are now supported in shared data

- include/vecmath/dag_vecMath.h
- include/vecmath/dag_vecMathDecl.h
- include/vecmath/dag_vecMath_common.h
- include/vecmath/dag_vecMath_const.h
- include/vecmath/dag_vecMath_neon.h
- include/vecmath/dag_vecMath_pc_sse.h
- include/vecmath/dag_vecMath_trig.h
Added support of some new compilators
Added float<>half converters
Fixed v_round and added v_round_ieee
> Update vecmath to upstream 08.04.25

- src/ast/ast_unused.cpp
```
options gen2
require daslib/lint
struct AutoSpawnPointData {}
def get_custom_respawn_groups() {
return table<int; AutoSpawnPointData>()
}
[export]
def main() {
let for_bot = false
var respawnGroupsEmpty : table<int; AutoSpawnPointData> // this is now access_ref!!!!
var customRespawnGroups <- for_bot ? get_custom_respawn_groups() : respawnGroupsEmpty
debug(customRespawnGroups)
}
```
> handle move initialization

- examples/profile/test_profile.cpp
- examples/profile/test_profile.h
- include/daScript/ast/ast.h
- include/daScript/daScriptModule.h
- include/daScript/misc/platform.h
- include/daScript/simulate/simulate.h
- include/daScript/simulate/simulate_fusion.h
- src/ast/ast.cpp
- src/ast/ast_module.cpp
- src/ast/ast_parse.cpp
- src/ast/ast_tls.cpp
- src/builtin/module_builtin_runtime.cpp
- src/misc/free_list.cpp
- src/simulate/runtime_string.cpp
- src/simulate/simulate.cpp
- src/simulate/simulate_fusion.cpp
Why: to make possible create custom thread local impl as example for fibers or coroutines
> Change thread local interface

- src/parser/ds2_lexer.cpp
- src/parser/ds2_lexer.lpp
- src/parser/ds2_parser.hpp
- src/parser/ds2_parser.ypp
- src/parser/ds_lexer.cpp
- src/parser/ds_lexer.lpp
- src/parser/ds_parser.hpp
- src/parser/ds_parser.ypp
- utils/dasFormatter/ds_parser.hpp
- utils/dasFormatter/ds_parser.ypp
There already exist include with typedef FLOAT, so change name from FLOAT to DAS_FLOAT
https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types
> Fix compilation error with Microsoft include

- daslib/debug.das
- examples/test/decs/decs_tests.das
- examples/test/misc/json_example.das
- examples/w3dold/app_opengl_glfw.das
- modules/dasTelegram/godfather/godfather.das
- tests/decs/test_gc.das
- utils/daScript/main.cpp
> Add support for version 2 make syntax and update command-line options

- src/ast/ast_infer_type.cpp
- src/parser/ds2_parser.cpp
- src/parser/ds_parser.cpp
- utils/dasFormatter/ds_parser.cpp
> empty ctor are no longer generated

- src/ast/ast_infer_type.cpp
```
typedef DressException = table < string; array < string >>
let shared emptyDressException <- DressException() // now ok
```
> Foo() into default<Foo> for aliases

- include/daScript/misc/hash.h
- include/daScript/misc/platform.h
to get unique tags for thread_local variables
> refactor: update DAS_THREAD_LOCAL macro to include variable names

- include/daScript/ast/ast.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
also linter option to check for super initializer
> super initializer

- src/ast/ast_infer_type.cpp
```
class A {
def A {
debug("A.A")
}
def tick(v : int) {
debug("A.tick")
}
}
class B : A {
def B {
super()  // call parent initializer
debug("B.B")
}
def override tick(v : int) {
super.tick(v) // call parent method
debug("B.tick")
}
}
[export] def main() {
var b = new B()
b.tick(13)
}
```
> support for super. no need for 'self'

- src/ast/ast_allocate_stack.cpp
this is now ok, even with _return_with_lockcheck CMRES
```
def make1234 {
var a <- [1, 2, 3, 4]
return <-a
} finally {
delete a
}
```
> if there is finally section in the current scope somehow - no CMRES

- include/daScript/ast/ast.h
- include/daScript/simulate/debug_info.h
- src/ast/ast_parse.cpp
- utils/dasFormatter/fmt.cpp
- catch duplicated modules
- use actual module names
> Refactor module name handling in prerequisite functions

- src/parser/parser_impl.cpp
> do not fail on empty sequence

- .github/workflows/build.yml
- daslib/_aot_generated/dasAotStub_ast_boost.das.cpp
- daslib/_aot_generated/dasAotStub_json.das.cpp
- daslib/_aot_generated/dasAotStub_json_boost.das.cpp
- daslib/_aot_generated/dasAotStub_math_boost.das.cpp
- daslib/_aot_generated/dasAotStub_random.das.cpp
- daslib/_aot_generated/dasAotStub_regex.das.cpp
- daslib/_aot_generated/dasAotStub_regex_boost.das.cpp
- daslib/_aot_generated/dasAotStub_strings_boost.das.cpp
- daslib/_aot_generated/dasAotStub_templates_boost.das.cpp
- daslib/_aot_generated/dasAotStub_utf8_utils.das.cpp
- src/ast/ast_aot_cpp.cpp
- src/simulate/simulate_fn_hash.cpp
We have global aot library, but there can be multiple contexts, so mangled name hash is no unique globally anymore.
> Revert hashes.

- src/ast/ast_infer_type.cpp
> check if value has valid type too

- src/ast/ast_infer_type.cpp
> clone can mismatch

- src/ast/ast_infer_type.cpp
> safe_when_uninitialized for global variables

- src/ast/ast_generate.cpp
```
def like_coroutine() {
return <- generator<bool> () <| $() {
for (i in get_array()) { // THIS NOW CREATES TEMP VARIABLE FOR THE SOURCE EVAL RESULT
print("")
for (j in get_array()) { // THIS NOW CREATES TEMP VARIABLE FOR THE SOURCE EVAL RESULT
print("j={j}\n")
yield true
}
yield true
}
return false
}
}
```
> fix bug in generator of the for loop for the regular arrays

- include/daScript/ast/ast.h
- src/ast/ast.cpp
- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
- src/ast/ast_module.cpp
- src/ast/ast_print.cpp
- src/ast/ast_simulate.cpp
- src/simulate/simulate.cpp
make sure no options left behind
> options with policy name harmonization

- examples/test/runtime_errors/return_reference.das
- include/daScript/simulate/debug_print.h
- modules/dasPEG/peg/parser_generator.das
- src/ast/ast_generate.cpp
use hash of block instead of address
disable jit for test
fix peg
add location to ast_generate
> Bunch of small improvements

- daslib/json_boost.das
- daslib/static_let.das
> support for enum_as_int, embed, unescape
