- src/ast/ast_parse.cpp
Reverse don't work for complex dependencies. Build prerequisits in right
order
> fix collect prerequisits

- examples/profile/main.cpp
- include/daScript/misc/arraytype.h
- include/daScript/misc/smart_ptr.h
- include/ska/flat_hash_map.hpp
- std::hash is not visible when compiling with clang 10.0.0
- std::out_of_range is not visible on both clang 10.0.0 and gcc 10.1.0
- template specilization must be placed in namespace where template is
defined (gcc with -fpermissive)
error: explicit specialization of ‘template<class TT> struct das::typeName’ outside its namespace must use a nested-name-specifier [-fpermissive]
33 | struct typeName<ObjectArray> {
> fix linux gcc and clang compilation

- include/daScript/misc/memory_model.h
- src/simulate/runtime_string.cpp
- recursive deletion of HeapChunk list leads to stack overflow
- passing a non-ASCIIZ string to allocateString() leads to buffer overflow in internMap.find() which ignores the length
> crash fixes

- doc/source/reference/language/arrays.rst
- doc/source/reference/language/builtin_functions.rst
- doc/source/reference/language/clone.rst
- doc/source/reference/language/expressions.rst
- doc/source/reference/language/functions.rst
- doc/source/reference/language/lambdas.rst
- doc/source/reference/language/statements.rst
- doc/source/reference/language/string_builder.rst
- doc/source/reference/language/structs.rst
- doc/source/reference/language/tables.rst
- this - видимо зарезервировано, хотя не указано в списке зарезервированных слов, выдает ошибку при попытке использования
- некоторые присваивания копированием невозможны (динамические массивы и таблицы), заменены на move
- поправлены обнаруженные опечатки
> corrections of typos

- src/builtin/builtin.das
Annotate each_enum function with unused_argument(tt) because tt is not used in function's body.
tt is used only for getting its type.
> Annotate each_enum function with unused_argument(tt)

- examples/test/unit_tests/string.das
- src/builtin/module_builtin_string.cpp
- fix crash when pass empty line (`float("")` for example)
- strings with additional spaces are valid for now ("  12" or "12  ")
- more tests
> improve numerical parsers

- include/daScript/misc/platform.h
`__builtin_clz` appears to be defined on MSVC C++17, so the definition here prevents compiling in a C++17 project.
> Prevent builtin redefinition on MSVC with C++17

- doc/source/reference/language/datatypes.rst
- src/builtin/module_builtin_fio.cpp
module_builtin_fio binds ref_time_ticks and get_time_usec functions.
These functions fail to AOT compile due to missing definitions.
The include has to be added somewhere.
> Add missing include for ref_time_ticks and get_time_usec

- doc/reflections/das2rst.das
- doc/source/stdlib/detail/math.rst
- doc/source/stdlib/math.rst
- include/daScript/simulate/aot_builtin_math.h
- include/daScript/simulate/sim_policy.h
- src/builtin/module_builtin_math.cpp
* reliable versions of isnan() and isfinite()
* abs() now accepts int and vectors
used functions v_cmp_le and v_cmp_lt requires this pull request: GaijinEntertainment/vecmath#3
> math: add sign(), isfinite(), improved abs()

- src/builtin/module_builtin_fio.cpp
usleep requires usec as parameter
> fio: fix sleep time on non-windows platforms

- src/misc/network.cpp
more info
https://stackoverflow.com/questions/40512274/release-udp-port-used-by-dead-process-on-os-x
> ability to reuse a socket immediately on macos

- include/daScript/simulate/aot_builtin_string.h
builtin_find_first_char_of2 function wasn't present in the header file, which made it impossible to use it in AOT mode
> builtin_find_first_char_of2 added to aot header

- include/daScript/simulate/aot_builtin_string.h
- src/builtin/module_builtin_string.cpp
There are situations when you need to set the length of the comparable string
> string: starts_with func overload with settable length of cmp str

- include/daScript/simulate/debug_info.h
- include/daScript/simulate/debug_print.h
Added a flag to be able to print both fixed size and scientific styles for float and double numbers.
> add fixedFloatingPoint printflag for debug printer

- include/daScript/ast/ast.h
Explicit bitwise OR operation will help you easily write combinations of SideEffects flags like:
`das::SideEffects::modifyArgument | das::SideEffects::invoke`
instead of
`das::SideEffects(uint32_t(das::SideEffects::modifyArgument) | uint32_t(das::SideEffects::invoke))`
> SideEffects combinations

- daslib/live.das
- examples/test/unit_tests/time.das
- include/daScript/simulate/aot_builtin_time.h
- src/builtin/module_builtin_fio.cpp
1) Added cast Time to int64
2) Now Time Sub method return a double, not a float
> daScript: Improve Time api

- doc/source/stdlib/detail/builtin.rst
Added documentation for get_clock.
Taked from: https://www.cplusplus.com/reference/ctime/time/
> Documented get_clock api

- src/ast/ast_aot_cpp.cpp
Use proper macroses ([U]INT64_C()) instead of hardcode suffixes.
This is required since this suffixes are actually platform specific
(depend on sizeof [u]int64 - it might be long (posix) or long long
(MS-based platforms)), macroses are more portable way to do it
> improve uint64/int64 immediate consts gen (aot)

- include/daScript/simulate/aot_builtin_matrix.h
- src/builtin/module_builtin_math.cpp
inline some of commonly used float3x4 functions both to speed-up
non WPO/LTO builds AND to bring closer dev & release
configurations
> inline couple of float3x4 matrix functions

- daslib/das_source_formatter.das
Since we want to add formatting validation to das scripts, we also need a mechanism that allows us to quickly exclude individual files from formatting. In this regard, it was proposed to add special formatting tokens starting with a prefix "//fmt:". The first such token is "//fmt:ignore-file" which can disable the formatting of the current file.
> das formatter: special tokens and ignore file feature

- include/daScript/ast/ast_handle.h
- src/ast/ast_handle.cpp
For the more correct initialization of inherited type annotations, we need to be able to pass the parent annotation to the BasicStructureAnnotation directly and not by its name (avoiding unnecessary findAnnotation by name call).
> Set BasicStructureAnnotation parent annotation by pointer

- include/daScript/simulate/simulate.h
- src/simulate/simulate.cpp
This commit implements a functionality of daScript "worker" contexts.
The main task of these contexts is to perform part of the work in worker threads for the daScript entity component system queries(One worker context per one worker thread).
These contexts can be created in advance, can have their own local stack and heap, and can share global constants with origin context(read only).
So during the MT execution, all we need is to choose the worker context corresponding to the current worker thread and execute for it makeWorkerFor method by passing there a pointer to the origin context. In the main thread, we just use the origin context.
> worker contexts feature

- include/daScript/simulate/cast.h
cast::from<float3> and cast::from<int3> functions uses _mm_loadu_ps(v_ldu) instruction to load data, which load 16 bytes instead of 12 required and as a consequence - it creates possible data race on last 4 bytes.
So in thread sanitizing mode, we will read exactly 12 bytes via memcpy in order to avoid TSAN data race warnings, and in production mode - will keep _mm_loadu_ps(v_ldu) for the best performance.
> cast<float3>::from and cast<int3>::from TSAN data race warning fix

- utils/daScript/main.cpp
useful flag to determine when the dascript utility was used
> dascript utility always set is_in_aot

- examples/test/test_threads.cpp
on ubuntu22.04 with system gcc11
```bash
cmake -Bbuild -S. -DDAS_CLANG_BIND_DISABLED=ON -DDAS_GLFW_DISABLED=ON -DDAS_STDDLG_DISABLED=ON -DDAS_STBIMAGE_DISABLED=ON -DDAS_STBTRUETYPE_DISABLED=ON
cmake --build build
```
I got this error
```
[ 84%] Building CXX object CMakeFiles/daScriptTestThreads.dir/examples/test/test_threads.cpp.o                                             
/usr/bin/c++ -DSIZE_OF_VOID_P=8 -DURIPARSER_BUILD_CHAR -DURI_STATIC_BUILD -I/home/mx/repos/daScript/include -I/home/mx/repos/daScript/examples/test -I/home/mx/repos/daScript/3rdparty/uriparser/include -Wno-invalid-offsetof -flto -fno-fat-lto-objects -Wno-ignored-attributes -MD -
MT CMakeFiles/daScriptTestThreads.dir/examples/test/test_threads.cpp.o -MF CMakeFiles/daScriptTestThreads.dir/examples/test/test_threads.cpp.o …
```
> add missing <thread> for gcc

- CMakeLists.txt
- examples/tutorial/CMakeLists.txt
- Rename DASCRIPT_MAIN_SRC to DAS_DASCRIPT_MAIN_SRC,
for make same prefix for all external options or defition
- Make DAS_DASCRIPT_MAIN_SRC as global (visible outside) to
avoid write native aot src files path by hand
> Improve CMake Config, set DASCRIPT_MAIN_SRC as global

- src/builtin/module_builtin_fio.cpp
MS-specific. getchar is declared as __cdecl so when building with
fastcall (x86) or vectorcall (x64) it can't be binded as is, so use
wrapper/ship to workaournd it
> builtin/fio: fix compilation with non std calling convention

- include/daScript/misc/smart_ptr.h
- src/ast/ast_infer_type.cpp
...instead of std specialization. Compatible both with std & eastl.
PS: old implementation was accidently dependand on bug of eastl's hash implementation
> explicit hash class for smart_ptr

- include/daScript/simulate/debug_info.h
- src/ast/ast_aot_cpp.cpp
- src/ast/ast_debug_info_helper.cpp
Make strings of all structs in debug_info.h const.
This both fix compilation errors like e.g.
XXX(NNN): error C2440: 'initializing': cannot convert from 'initializer list' to 'das::FuncInfo'
(in msvc+/permissive-) and simplifies overall code as well (e.g. remove need for manual casts)
Also fix incorrect 64 bit hashes on 32 bit MS-platforms (unsigned long is 32 bit on win32,
use appropriate macro UINT64_C instead)
> fix aot debuginfo strings const-correctness

- src/builtin/module_builtin_jobque.cpp
- src/builtin/module_builtin_network.cpp
Server::shutdown used to be called more often, than Server::startup. Because needShutdown was set to true once and was never unset. This resulted in fatal error on Windows.
Also, g_jobQueTotalThreads shouldn't be zeroed because it screws up the counter logic.
> Fix unmatched Server::shutdown calls

- include/daScript/simulate/aot_builtin_jobque.h
- src/builtin/module_builtin_jobque.cpp
Added channel_create/channel_remove unsafe functions (require for using channels with coroutine macro + threads - otherwise if channel lives only inside block, there is no way to yield from this block)
Example of using:
https://gist.github.com/spiiin/b924517f1c0db7f1e08d9f7e9e2512fa
> channel_create/channel_remove

- include/daScript/simulate/aot_builtin_math.h
#pragma float_control` is documented in the Clang extensions manual but doesn't seem to be supported on arm64
> disable float_control on arm64 platforms

- include/daScript/ast/ast_handle.h
- include/daScript/simulate/aot.h
Method allows to push default-constructible, but non-local elements into CPP vectors
> push_empty method for vector bindings

- daslib/das_source_formatter.das
Old:
```
def func(a : int;
t : tuple<
b : int;
c : int;
>)
// ...
```
New:
```
def func(a : int;
t : tuple<
b : int;
c : int;
>)
// ...
```
> Formatter: better handling of multi-line tuple function parameters

- src/ast/ast.cpp
hasNonTrivialCtor, hasNonTrivialDtor, hasNonTrivialCopy traits bug fixed
they are inclusive, i.e. if any field has - entire structure has
> fixing bug in traits

- daslib/templates_boost.das
- src/ast/ast_infer_type.cpp
var b <- new [[ExprOp2() op:="+"]]
var a <- [{ExpressionPtr[1] b}]
b should be null
> fixing array construction - moveable elements need to be moved

- daslib/ast_block_to_loop.das
- src/ast/ast_block_folding.cpp
cond return with move semantics now preserves semantics example of the usage to follow
> cond return with move semantic no longer folds for smart_ptr

- .github/workflows/msvc.yml
- CustomRules.ruleset
Code analysis now excluding some warning types (C26451 and C26495)
> Excluded 2 warning types from Code analysis action

- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
- src/ast/ast_simulate.cpp
- tests/language/global_variable_order.das
some global constants fold immediately
> global variable initialization order check

- .github/workflows/build.yml
- .github/workflows/wasm_build.yml
Now if we have two workflow rans from pull-request and push at the same time, then only the push one will be skipped.
> Small fix to workflows skipping

- src/ast/ast_infer_type.cpp
lets properly initialize [[Foo()]]
> lets not crash on duplicate generic instance 'in flight'

- daslib/enum_trait.das
to get an array with strings of all names from enum. This is useful to print stuff for cases when actual enum value is stored as an int. we dont have a way to convert ints to enum fastly right now
> added enum_names typeinfo macro for enums

- src/builtin/builtin.das
Sort with default cmp would access first element of the array even if it's empty
> Fix out of range array access in builtin sort

- include/daScript/simulate/simulate.h
This commit fixes binary incompatibility of das::Context structure in mixed mode (when only simulate_exceptions.cpp is built with exceptions incl. DAS_ENABLE_EXCEPTIONS=1)
Follow-up to https://github.com/GaijinEntertainment/daScript/pull/529
> allow to build with exceptions only one module (mixed mode)

- src/builtin/module_builtin_debugger.cpp
Native name is different from das one. This fixes aot builds
> fix Prologue::block native member name

- include/daScript/simulate/aot.h
- include/daScript/simulate/simulate.h
To prevent it being inlined in LTO/WPO mode (which breaks exceptions)
> mark all exception catching functions with noinline

- src/simulate/simulate.cpp
pass skipLockChecks flag to workers
> skip lock checks in sub contexts too

- include/daScript/ast/ast.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_print.cpp
- src/builtin/module_builtin_ast_flags.cpp
- src/builtin/module_builtin_debugger.cpp
- src/parser/parser_impl.cpp
- tests/language/failed_capture_self.das
we may revisit the problem later, if it indeed becomes a serious limiter
its possible to do ctor in the ascended memory, and not to do the move. probably
> can't capture 'self' in the class initializer (it will be moved afterwards)

- include/daScript/ast/ast_handle.h
This is a warning generated when building with `-std=gnu++20`
[build] warning: ‘template<class _Tp> struct std::is_pod’ is deprecated: use is_standard_layout && is_trivial instead [-Wdeprecated-declarations]
[build]   246 |             return is_pod<OT>::value;
[build]       |                    ^~~~~~
> Fix compile time warning for POD test.

- daslib/das_source_formatter.das
> das_source_formatter: fix format after 'match_type'

- src/builtin/module_builtin_runtime_lockcheck.cpp
functions should return previous value,
but currently result is inverted
> second try to fix verify lock functions

- include/daScript/simulate/aot_builtin_math.h
clang can't apply float_control/attribute to inlined function
> fix stripped fisnan/fisfinite in clang builds

- include/ska/flat_hash_map.hpp
There is also num_elements present as a class field. Came up as a warning. Not sure how it did not before.
> Do not shadow class field

- daslib/json_boost.das
https://github.com/GaijinEntertainment/daScript/issues/716
> fix from_JV for parse struct field which not exist in json

- src/ast/ast_infer_type.cpp
syntactically its possible to put lambda in there. its now an error
> can only pipe block into local declaration

- daslib/coroutines.das
This pull request fixes an issue with coroutines in the codebase. Specifically, it ensures that the `visit` function in the `YieldFrom` class correctly verifies that the argument passed to it is an iterator before continuing. This fix improves the reliability and stability of the codebase.
> Fix coroutines

- include/daScript/ast/ast_handle.h
This commit allows to register vector types for non-copyable items. Now registerVectorFunctions doesn't require item type to have copy constructor when it tries to add push_back methods.
> Fix vector binding for non-copyable types

- src/simulate/simulate.cpp
Before we don't call onInstall for thread local debug agent,
but call for other agents
> Fix thread local debug agent install

- daslib/profiler.das
Now we can print to log profiler result in
second/millisecond/nanosecond time unit format
> Improve profiler time output

- include/daScript/ast/ast_visitor.h
- include/daScript/simulate/aot.h
- include/daScript/simulate/data_walker.h
- include/daScript/simulate/interop.h
- include/daScript/simulate/simulate_nodes.h
- src/ast/ast_aot_cpp.cpp
- utils/daScript/main.cpp
LCC compiler used for Elbrus2000 (e2k) CPU architecture mimics GCC but don't support some pragmas so we add LCC-specific pragmas to suppress/restore warnings for this compiler (detected by `__EDG__` predefined macro)
> support suppressing warning for LCC compiler (e2k CPU arch)

- include/daScript/simulate/bind_enum.h
Problem: you cannot create enums that have backticks in das name (for example, ```Node`ProcessMode```) because macro `DAS_BASE_BIND_ENUM` creates structure
```
class Enumeration##das_enum_name : public das::Enumeration
```
which is invalid when desired das name contains symbols that cannot be used in C++ identifiers
Solution: add new macro `DAS_BASE_BIND_ENUM_SAFE` which takes additional c++-safe name that will be used in annotation name. Original `DAS_BASE_BIND_ENUM` macro must stay untouched for compatibility
> Support enums with symbols that cannot be used in C++ identifiers

- src/builtin/module_jit.cpp
Replace hardcoded llx with PRIx64
why: uint64_t not always a unsigned long long
> Fix compilation module jit

- include/daScript/ast/ast_generate.h
- src/ast/ast.cpp
- src/ast/ast_generate.cpp
- src/ast/ast_infer_type.cpp
walk block arguments and return type only for closures
> improve error messages when block is not fully inferred

- include/daScript/misc/platform.h
- src/misc/sysos.cpp
To build for Windows-on-ARM64 with VC that doesn't have some X64-related intrinsics and X64 registers
> allow building for arm64 for windows platform (vc2019, vc2022 and clang)

- src/ast/ast_parse.cpp
In big projects there might be multiple files with the same module name. Currently we just silently ignore the second file.
> verify that module names are unique

- include/daScript/simulate/debug_info.h
- src/ast/ast_parse.cpp
- src/builtin/module_file_access.cpp
comparing to isModuleAllowed this function calls before resolving the native/shared modules
> Add canBeRequired method to ModuleFileAccess

- include/daScript/ast/ast.h
- src/ast/ast_module.cpp
- src/builtin/module_builtin_ast_serialize.cpp
This allows us to check for changes in bindings in builtin modules
> compute cumulative hash for native builtin modules

- include/daScript/simulate/aot.h
Using non const methods of vector might be slower/incur additional ovehead.
Dowstream Change-Id: I2bbcd242a4b5787f2900589abf0a84f217baf5f1
> fix `das_vector_each_sequence` const correctness

- modules/dasClangBind/bind/bind_imgui.das
This binding configuration change is needed for the Dear ImGui [update](https://github.com/borisbat/dasImgui/pull/5) in the dasImgui module.
> Update Dear ImGui to v1.90.6

- daslib/algorithm.das
- examples/test/misc/any_alg.das
Fix an error:
```
Compilation error: daScript/daslib/algorithm.das:142:52:
return lower_bound(temp_array(a), f, l, value, less)
^^^^^
142:52 - 142:57
30305: can't locate variable value
```
> Fix lower_bound algorithm

- include/daScript/misc/string_writer.h
- include/daScript/simulate/aot_builtin_string.h
We should use fmt::runtime for non constant string or we will get a compile error if the string cannot be evaluated in constexpr
I use fmt::runtime in StringWriter::format, due it public and can be used anywhere in user code. But that possible to make it consteval by using fmt::format_string as argument instead of char*
Example: https://godbolt.org/z/zjTefj5eM
> Fix: format not a constant expression

- tests/language/operators.das
- tests/language/operators_derived.das
- tests/language/operators_parent.das
Hi!
I run upon a case where you are not able to call inherited `operator .` function because of `field not found in (30503)`.
I have added test case for the issue in this PR.
The case seems to be like this:
File_A: declare base `class (A)` with `operator .`
File_B: declare derived `class B` from `class A`
File_C: `require File_B`, declare variable of type `class B` and call  `operator .` (it should be there because `class B` is derived from `class A`)
It is fixable by requiring `File_A` in `File_C` (along with `File_B`) but I suppose it is not how it was intended to work.
> Inherited 'operator dot' is not callable when declared in separate file

- src/ast/ast_handle.cpp
- src/ast/ast_infer_type.cpp
```
typedef noclone = lambda<(a:int):void>
struct Foo
a : noclone
b : array<noclone>
[export]
def main
var a : Foo
var b := a
```
reports
```
var b := a
^
10:5 - 10:6
30507: local variable b of type Foo can't be cloned from Foo& -const
can't clone Foo&.a : lambda<(a:int const):void> aka noclone
can't clone Foo&.b[] : lambda<(a:int const):void> aka noclone
```
> descriptive clone errors

- include/daScript/ast/ast.h
- include/daScript/ast/ast_expressions.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
- src/builtin/module_builtin_ast_flags.cpp
- src/builtin/module_builtin_ast_serialize.cpp
- src/builtin/module_builtin_rtti.cpp
```
struct Box
min, max : float2
def operator . size ( var self:Box )
return self.max - self.min
def operator . center := ( var self:Box; at:float2 )
var size = self.size
self.min = at - size * 0.5
self.max = at + size * 0.5
[export]
def main
var box = [[Box min=float2(-1,-1), max=float2(1,1)]]
box.center = float2(2,2) // note: NOT A CLONE
print("box = {box}\n")
```
assumming "options strict_properties" or policy is not set
> a.PROPERTY = value now promotes to a.PROPERTY := value automatically

- src/ast/ast_aot_cpp.cpp
When generating size/offset static_asserts for AOT, the raw das name of structs which can contain stuff like grave and tildae. Instead, we have to use aotStructureName to get the mangled name with no special characters.
> Fix AOT for structures with special chars in names

- include/daScript/simulate/aot.h
One of the possible forms of invoking a block from AOT codegen code is das_invoke<ResType>::invoke<ArgTypes...> (or same with invoke_cmres). What we actually pass to this function can be different depending on the context: an actual Block object, OR a **C++ lambda**.
When passing a lambda, we have no choice but to use template argument deduction. But that was completely broken, as the lambda type BLK was specified as the first template argument for invoke/invoke_cmres and so AOT codegen tried to specify the lambda type as some argument type instead.
Moving the BLK template parameter to be the last one seems to fix the problem. BUT! It brings a new problem, now the templated overload becomes preferable over regular overloads when upcasting the block to a parent type.
To fight the new …
> Fix block invoke AOT codegen not compiling sometimes

- src/ast/ast_infer_type.cpp
- src/builtin/module_builtin_rtti.cpp
'under clone field type not inferred yet' is no longer an error
> its not an error. its an idea that compiler will take one more pass

- include/daScript/ast/ast.h
- src/ast/ast_allocate_stack.cpp
- src/ast/ast_lint.cpp
- src/builtin/module_builtin_ast_serialize.cpp
- src/builtin/module_builtin_rtti.cpp
```
options no_fast_call
def fib ( n ) // no longer [fastcall] via option
if n <= 1
return n
return fib(n-1) + fib(n-2)
```
> disable fastcall with option or COP

- daslib/templates_boost.das
Oops, I messed it up previously, the compiler didn't even try executing the concept_assert because of missing return and unused arguments. Also added printing of the type.
> Fix invalid $t reification type error message

- daslib/apply.das
- tests/apply/test_apply.das
adds assume argName = name at the front of the block, remove first argument of the block. that way name is constexpr
> apply now assumes name. there is no variable

- src/misc/sysos.cpp
Do use just `vector` instead of `std::vector` as later may be unavailable due to global config alias.
Downsteam Change-Id: I0e3e7e625ec6b7b954dce90df97b303b4ea9bcc9
> fix windows sysos.cpp compilation in case of non-std vector usage

- examples/test/misc/padd.das
- examples/test/misc/padd_example.das
- src/ast/ast_infer_type.cpp
- src/ast/ast_typedecl.cpp
```
require padd
def take_foo ( foo : $padd_dim(type<auto(TT)>,14) ) : TT
debug(foo)
return [[TT]]
[export]
def main
var foo : $padd_dim(type<float>,14)
print("foo = {foo}\n")
take_foo(foo)
```
> at least some infer for type macros

- include/daScript/ast/ast.h
- src/ast/ast.cpp
- src/ast/ast_allocate_stack.cpp
- src/ast/ast_derive_alias.cpp
- src/ast/ast_parse.cpp
- src/builtin/module_builtin_ast_serialize.cpp
this changes stack allocation strategy
its not longer 'all functions in the module, once the module is compiled'
its no only once per program (and once per macro module) - and only used functions and variables
> less stack

- include/daScript/simulate/simulate.h
- src/simulate/simulate.cpp
Why: This is very useful when we have a main context that does a lot of initialization and needs a large stack, but the copies use pre-prepared data so they don't need as much stack.
> Make possible to set custom stack size to copied context

- examples/test/compilation_fail_tests/circular_dependency.das
- src/ast/ast_typedecl.cpp
```
struct Foo
a : array<Foo>
```
is now ok
> array<FOO> and table<FOO> no longer circular dependency

- daslib/ast_boost.das
- daslib/contracts.das
- daslib/rst.das
- daslib/templates_boost.das
- daslib/typemacro_boost.das
- examples/test/unit_tests/reflection.das
- include/daScript/ast/ast_typedecl.h
- include/daScript/misc/arraytype.h
- include/daScript/simulate/aot.h
- include/daScript/simulate/data_walker.h
- include/daScript/simulate/debug_info.h
- include/daScript/simulate/debug_print.h
- include/daScript/simulate/heap.h
- include/daScript/simulate/jit_abi.h
- src/ast/ast.cpp
- src/ast/ast_aot_cpp.cpp
- src/ast/ast_infer_type.cpp
- src/ast/ast_typedecl.cpp
- src/builtin/debugapi_gen.inc
- src/builtin/debugger.das
- src/builtin/module_builtin_ast_serialize.cpp
- src/builtin/module_builtin_debugger.cpp
- src/builtin/module_builtin_misc_types.cpp
- src/builtin/module_builtin_rtti.cpp
- src/builtin/module_builtin_rtti.h
- src/builtin/module_builtin_runtime.cpp
- src/simulate/bin_serializer.cpp
- src/simulate/data_walker.cpp
- src/simulate/debug_info.cpp
- src/simulate/json_print.cpp
The code mostly copies the behavior of 16-bit enums, with some exceptions like alignemnt and sizeof parts.
> Support 64-bit enums

- src/simulate/simulate_exceptions.cpp
Why: this stack represent error, there no reason to write it to out, because other messages in this function we write to err
> Exception: write stack to err on exception

- daslib/ast_boost.das
- include/daScript/simulate/aot_builtin_ast.h
- src/builtin/module_builtin_ast.cpp
walk_and_convert_enumeration() used enum integer value as list index directly.
> Fixed crash when quoting enum value from enum with non-sequential values

- include/daScript/misc/runtime_table_utils.h
- include/daScript/simulate/aot.h
Usage:
```
static void test_string_string_table(const das::TTable<char *, char *> & table,
das::Context * context,
das::LineInfoArg * at)
{
das::for_each_table(table, [](const char * key, const char * value)
{
printf("%s -> %s", key, value);
return true;
}, context, at);
}
```
> Added wrapper to simplify iteration over das::Table in c++

- src/builtin/module_builtin_runtime_lockcheck.cpp
```
struct Foo
a : array<int>
struct Bar
b : array<Foo>
def fail_field
var a <- [[Foo a <- [1,2,3,4] ]]
for b in a.a
return <- a	// EXCEPTION: object type<Foo>.a contains locked elements and can't be modified (resized, pushed to, erased from, cleared, deleted, moved, or returned via move)
return <- a
def fail_array_index
var b : Bar
b.b |> emplace ( [[Foo a <- [1,2,3,4] ]] )
for a in b.b[0].a
return <- b	// EXCEPTION: object type<Bar>.b[0].a contains locked elements and can't be modified (resized, pushed to, erased from, cleared, deleted, moved, or returned via move)
return <- b
def fail_tuple_index
var b : tuple<Foo>
b._0 <- [[Foo a <- [1,2,3,4] ]]
for a in b._0.a
return <- b	// EXCEPTION: object type<tuple<Foo>>._0.a contains locked elements and can't be modified (resized, pushed to, …
```
> lockcheck returns path to where the issue is

- include/daScript/simulate/interop.h
On systems with LP64 datatype models int64_t typically is an alias for long, and is not the same as long long. When such a call happens, the most generic implementation of ImplCallStaticFunctionImpl is chosen, and it throws "internal integration error".
> fix binding functions returning [unsigned] long long

- src/builtin/builtin.das
Calling push with non-copyable argument caused "unused function argument" error, and not "can't push value, which can't be copied", while the latter was intended. This was because branch that actually uses the arguments was thrown away
> Fix misleading error in some built in array functions

- examples/test/misc/hello_world.das
- src/ast/ast_infer_type.cpp
```
tuple Tup {
a : int;
b : float;
c : string;
}
let c : tuple<int;float;string> = Tup(1,2.,"3");
```
in both syntaxes
> function-like named tuple initialization

- include/daScript/simulate/runtime_array.h
- include/daScript/simulate/simulate_nodes.h
- src/builtin/module_builtin_runtime_lockcheck.cpp
fix template code issues
add default case
> fix linter/compiler errors

- include/daScript/simulate/debug_info.h
- include/daScript/simulate/runtime_array.h
- include/daScript/simulate/runtime_range.h
- include/daScript/simulate/simulate.h
- src/ast/ast_simulate.cpp
> Keepalive take 2

- src/ast/ast_infer_type.cpp
```
class A
class B : A
[export]
def test()
var b <- [{A? [1] new B()}] // ok
var c <- [{A? [] new B()}] // ok
var a <- array<A?>(new B()) // now compatible
var d <- [{A ? new B()}] // now compatible
```
> allow substitute

- src/ast/ast_infer_type.cpp
we return first type, not default value type
ref comes from default value
const from both
> fix ExprNullCoalescing into returning correct type

- src/ast/ast_infer_type.cpp
```
class A
class B : A
[export]
def test()
var a : array<A?> <- array<A?>(new B()) 
var d : array<A?> <- [{A ? new B()}] 
```
now ok, because
```
var a : array<A?> <- to_array_move(cast<A?> new B)
```
> cast for single element array making

- include/daScript/ast/ast.h
- src/ast/ast_infer_type.cpp
- src/builtin/module_builtin_rtti.cpp
```
def return_array
return [1,2,3,4]    // auto-promotion to return <-
var q = [1,2,3,4]          // auto-promotion to q <- 
[export]
def main
var a = [1,2,3,4]		// allowing auto-promotion to a <-
a = [5,6,7,8]			// allowing auto-promotion to a <-
var blk = $ <|
return [1,2,3,4]	       // allowing auto-promotion to return <-
```
> allow relaxed assignment syntax

- src/ast/ast_allocate_stack.cpp
```
struct Foo
a : int = 10
def get() : Foo
return <- Foo()
[export]
def test(a : int?)
if a == null
return
var inscope foo <- get() // this one gets relocated on top of the block as uninitialized variable
debug(foo)
```
> relocated variables can be uninitialized

- examples/tutorial/CMakeLists.txt
- examples/tutorial/tutorial07.das
- examples/tutorial/tutorial07unaligned.c
- include/daScript/daScriptC.h
- src/misc/daScriptC.cpp
in some languages vec4f is not part of the C interop ABI.
use _unaligned version of the interfaces of those. 
some performance penalties may happen if arguments are not aligned.
> unaligned interop for the languages which do not support vec4f abi

- include/daScript/simulate/simulate.h
There a problem with exception if we catch it outside of das::Context scope we can get broken memory for 'what' pointer due the fact we storage exception message inside das::Context and put only pointer to exception
Because of that i would like to copy exception message to dasException I decide to use runtime_error, because:
`It reports errors that are due to events beyond the scope of the program and cannot be easily predicted.`
> Rework dasException

- src/ast/ast_infer_type.cpp
- src/ast/ast_print.cpp
```
options gen2;
require math;
[export]
def test() {
var f : float3;
let t = normalize(f);
let q = f.normalize(); // casting to undefined type auto, invalid swizzle mask
}
```
> fixing invalid swizzle mask on invoke

- examples/test/compilation_fail_tests/const_ref.das
- src/ast/ast_infer_type.cpp
- tests/language/named_call.das
relaxed_pointer_const can now be disabled in CodeOfPolicies
> const correctness for lambda fields. better error reporting

- include/daScript/simulate/simulate.h
Simulate.h uses std::string but doesn't include it directly which causes a compilation error with fresh libstdc++. Included misc/platform.h which seems to be the way to include das_config.h which includes & defines string stuff AND changed it to be das::string.
> Add missing include to simulate.h

- include/daScript/simulate/runtime_string.h
- src/ast/ast_infer_type.cpp
- src/simulate/runtime_string.cpp
```
error[30304]: no matching functions or generics: COOL(int const)
D:\Work\daScript/examples/test/misc/hello_world.das:26:1
COOL(1);
^^^^
COOL(int const)
while compiling: main: void
candidate function:
cool(a: int const): int at D:\Work\daScript/examples/test/misc/hello_world.das:20:4
name is similar, typo?
error[30503]: can only safe dereference a pointer to a tuple, a structure or a handle UnitTest::EntityId&
D:\Work\daScript/examples/test/misc/hello_world.das:29:14
var bar = eid?.Baz;
^^
?.`Baz(UnitTest::EntityId&) or (UnitTest::EntityId&, string)
while compiling: main: void
candidates:
operator ?.`Bar(e: UnitTest::EntityId const): int const at D:\Work\daScript/examples/test/misc/hello_world.das:8:4
name is similar, typo?
operator ?.`Baz(e: UnitTest::EntityId? const): int const at …
```
> we report mismatching functions better

- src/ast/ast_infer_type.cpp
```
let TILE_SIZE = int2(100);
[export]
def main
let w = TILE_SIZE.x * 10;
let h = TILE_SIZE.y * 10;
print("w: {w}, h: {h}"); // was w: 1000, h: 0 !!, now w: 1000, h:1000
```
> bug in vector folding

- include/daScript/ast/ast.h
- src/ast/ast_infer_type.cpp
- src/builtin/module_builtin_ast_flags.cpp
access_fold flag will be set if variable was used for folding during infer
> variable was accessed during const folding

- src/ast/ast_derive_alias.cpp
```
options gen2;
struct PlayerSetup {
forwardSpeed : float = 1.0;
};
struct PlayerState {
setup : PlayerSetup = PlayerSetup();
};
var player : PlayerState = PlayerState();
```
> lets not crash on alias derivations

- include/daScript/simulate/cast.h
Do init temp register as otherwise GCC 15 complains and fails to build in -Werror mode with
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: `v` is used uninitialized [-Werror=uninitialized]
29 |   return __builtin___memcpy_chk (__dest, __src, __len,
|          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
30 |                                  __glibc_objsize0 (__dest));
|                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
> fix GCC -Wwuninitialized warning/build in TSAN mode

- src/builtin/module_builtin_ast_annotations_3.cpp
Use proper c++ name in order to fix aot errors (caught in paranoid mode)
> fix `_capture` alias of `ExprMake{Block,Generator}'

- src/ast/ast_infer_type.cpp
Infinite apply in a pass macro (or more complicated macro scenarios) should no longer cause an infinite compilation loop.
> limit number of macro applies

- daslib/debug.das
> dap: invalidate breakpoints

- src/ast/ast_infer_type.cpp
- src/parser/parser_impl.cpp
```
class Base
def hello() : void
pass
class Derived : Base
def sealed hello()
pass
[export]
def main
unsafe
var base : Base? = new Derived()
```
> sealed is also override

- doc/source/daslang.py
sphinx rearranged code for python domain splitting it into smaller parts, so versions newer or equal 7.3.0 have this function in different place. Dagor has moved to sphinx 8+ for documentation and we need this change.
Sphinx8 has mostly deprecated string-like paths and is now (almost everywhere) using PathLike objects for which addition with strings is not possible, so f-strings are now required
> doc: support sphinx versions 7.3.0 and above

- include/daScript/simulate/cast.h
Do use memcpy-to-temp-var cast as it's portable, correct and fast
This fixes clang18 binding of inline functions that return vec3/Point3 and return special code path for TSAN.
> fix cast of vectypes with sizeof < vec4f (16)

- src/parser/parser_impl.cpp
parser_impl.cpp(75): warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
> Fix clang warning unqualified-std-cast-call

- src/ast/ast_const_folding.cpp
```
require math
def rad_to_deg(rad : float)
return rad * 180.f / PI
[export]
def main
print("{float2(rad_to_deg(180.f), 0)}") // no longer crashes on double fold within the same pass
```
> fix bug in const folding with double run

- examples/test/unit_tests/dummy.das
- src/ast/ast_infer_type.cpp
- tests/language/local_classes_failed.das
```
options gen2;
struct Foo {
def take() {
debug("foo")
}
}
class Bar {
foo : Foo // error
foo = Foo() // ok
@safe_when_uninitialized foo : Foo // ok
def test() {
foo.take()
}
}
[export]
def main() {
var a = new Bar()
a.test()
}
```
> member variables for structures and classes can be unsafe when uninitialized.

- src/ast/ast_infer_type.cpp
```
def take1
print("take1")
def take2
print("take2")
[export]
def main
var count = 0
count ++
count!=0 ? take1() : take2()  // NOW AN ERROR
```
> cond can't be void

- include/daScript/ast/ast.h
- src/ast/ast.cpp
- src/ast/ast_print.cpp
- src/builtin/module_builtin_ast_flags.cpp
- src/parser/parser_impl.cpp
```
struct Foo
a,b : int
def Foo
a = 1
b = 2
struct Bar
c : int
d : Foo // = Foo()
[export]
def main
var a = [[Bar() c=1]] // error[31300]: Uninitialized field d is unsafe.
debug(a)
```
> not calling default initializer is now a valid case for 'not initialized'

- src/ast/ast_export.cpp
```
[sideeffects]
def init_with_sideeffects
return 1
var @export a = init_with_sideeffects() // notice @export, variable is now forced to be 'used'
[export]
def main()
print("Hello, World!\n")
```
> support for global variable export annotation

- CMakeLists.txt
- src/parser/ds_lexer.cpp
- src/parser/ds_lexer.lpp
- src/parser/lex.yy.h
- utils/daScript/dasFormatter/ds_parser.ypp
- utils/dasFormatter/Readme.md
- utils/dasFormatter/ds_parser.cpp
- utils/dasFormatter/ds_parser.hpp
- utils/dasFormatter/ds_parser.ypp
- utils/dasFormatter/formatter.cpp
- utils/dasFormatter/formatter.h
- utils/dasFormatter/helpers.h
- utils/dasFormatter/main.cpp
This PR creates tool to transform from syntax v1 to syntax v2.
Main logic are in second commit.
Right now there's one problem:
we'll lose all comments and spaces/linebreak inside initialization expression:
```
[[A  /**/
a = 1]]
// will be converted to
A(a=1)
```
> Syntax formatter v1 v2

- include/daScript/misc/vectypes.h
- include/daScript/simulate/aot_builtin_math.h
Apparently use of `v_ldu_p3` (which in the end is expanded in simple `_mm_loadu_ps`) causing some compilers (*) to mis-optimize subj code (I guessing b/c of load past vector instance?) so use safe version which works reliably.
(*) e.g. clang18
Somewhat related to
https://github.com/GaijinEntertainment/daScript/pull/1457
> fix aot normalize(float3)

- include/daScript/misc/vectypes.h
Use memcpy-based implementation of subj fn as its' seems that it's generates much better code then `v_ldu_p3_safe`.
Basically continuation of
https://github.com/GaijinEntertainment/daScript/pull/1498
> speed-up vec3 load/vec4f conversion

- src/ast/ast_infer_type.cpp
```
enum A
B
def get_weapon_slot_at(a; limit = A.B) // now ok
return 42
def human_weapon_switch_input_es()
get_weapon_slot_at(1) // this infers
```
> better enumeration infer

- src/ast/ast_infer_type.cpp
```
enum e
one = 1
two = 2
[export]
def main
print("{int(e.one)}\n")
```
> this infers

- include/daScript/simulate/heap.h
* Allow to pass externally allocated memory pointer into subj ctor. To be used for externally controlled memory allocation strategy
* Remove virtual dtor as there is no polymorphism used so it's waste of space/code
> improve/extend StackAllocator a bit

- daslib/das_source_formatter.das
fix this case:
let x = '{'
let y = '\t'
> formatter: fix detection of string interpolation inside characters

- include/daScript/misc/string_writer.h
- src/ast/ast_aot_cpp.cpp
It's unclear how they should operate, which makes it easy to introduce bugs
> Remove copy/move constructors in TextWriter

- include/daScript/daScriptBind.h
- src/builtin/module_builtin_uriparser.cpp
These macros cover most of the cases, when binding CPP functions and classes. They also don't require this functions to be linked, when building AOT compiler, only function declarations are required in this case, and stubs are generated and bound
In this commit:
- include/daScript/daScriptBind.h contains all new macros and instructions on how to use it
- module_builtin_uriparser.cpp is refactored as an example usage of some of new macros
> Add macros for simplified bindings and auto stub generation

- daslib/das_source_formatter.das
fix this case:
def f(x : block<() : bool>)
> formatter: fix spaces around <> after 'block'

- daslib/match.das
- src/ast/ast_infer_type.cpp
- tests/decs/failed_test_arguments.das
```
error[40104]: match argument a.foo failed to compile
D:\Work\daScript/examples/test/misc/hello_world.das:10:11
match a.foo
^
```
> match error reporting to be sane

- include/daScript/daScriptBind.h
- src/builtin/module_builtin_uriparser.cpp
… to PR #1529)
All changes:
- Fixed compilation error of stubs for reference-returning functions
- Optimized compilation time of underlying templates for DAS_METHOD_DECL/DAS_PROP_DECL/DAS_PROP_DECL_CONST
- DAS_PROP_DECL/DAS_PROP_DECL_CONST will now select method overload with no arguments in case of several overloads, without manually specifying it
- DAS_ADD_PROP_BIND/DAS_ADD_PROP_BIND_CONST now uses addPropertyForManagedType instead of addProperty, so it will not attempt to bind parent classes
- Fixed DAS_PROP_DECL_CONST not working correctly with addPropertyExtConstForManagedType when building AOT compiler
- Fixed MSVC was generating inline function code, even if it was stubbed, resulting in linker errors (only evaluate function pointers inside decltype)
- Fixed all encountered MSVC …
> Sync all fixes and improvements to daScript/daScriptBind.h

- include/daScript/ast/ast_interop.h
- include/daScript/daScriptBind.h
- include/daScript/simulate/aot.h
This commit enables automatic stubbing for addCtor/addCtorAndUsing and vector function bindings. It is also can be generalized for something else
- Added das::is_stub_type templated structure, that is meant to be used, to signal, if functions, related to the type, should be stubbed
- BuiltIn_PlacementNew, BuiltIn_Using for stubbed types will be stubbed
- das::das_vector_* functions for stubbed item types will be stubbed
- For types, bound with DAS_DECL_TYPE, specialize das::is_stub_type to be true in AOT compiler
> Stub constructor/using and vector functions if required

- include/daScript/ast/ast_typedecl.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_typedecl.cpp
we can now always use
TypeDecl::clone ( a, b )
instead of
a = make_smart<TypeDecl>(*b)
in fact upcoming is full refactor like that
> Opt malloc

- include/daScript/ast/ast.h
- include/daScript/misc/platform.h
- include/daScript/misc/safebox.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_module.cpp
- src/builtin/module_builtin_ast_serialize.cpp
fragile caches are used. they are faster due to not storing key, only hash of key, and assuming its unique. we already do that for functionsByName, so its only a real change for function lookups.
> Custom unique hashes for functionsByName and function argument lookups

- include/daScript/daScriptBind.h
1. Now ADD_FUN/METHOD_BIND will automatically select appropriate simulation node: SimNode_ExtFuncCallRef if result is a reference, SimNode_ExtFuncCall otherwise (In case of returning by value it is still up to the user, attempt to determine this automatically too by using has_cast has shown that it is not viable)
2. DAS_MODULE_DECL_EX can now accept several include paths, each of them can contain quotes (either " or <) or not (" used by default)
3. Rework asserting stub, it will now not link copy constructor, and will always crash after assert by calling nullptr instead of returning garbage and possibly continue execution
4. Fixed DAS_ADD_USING_BIND
Change-Id: I0eeac047b60d72f03ebe9009ae0dd8b9782f0419
> Another pack of improvements to daScript/daScriptBind.h

- daslib/type_traits.das
Here is the example
```
options gen2;
require daslib/type_traits;
class Base {
}
class B : Base {
}
class C : Base {
}
class D {}
def someThing ( blk : block < ( arg : auto(TT) ) : void > ) {
static_if ( typeinfo is_class(type<TT>) ) {
static_if ( is_subclass_of(type<TT>, type<Base>) ) {
print("arg is {typeinfo typename(type<TT>)}\n")
} else {
concept_assert(false, "{typeinfo typename(type<TT>)} is not subclass of Base");
}
} else {
concept_assert(false,"{typeinfo typename(type<TT>)} is not a class at all")
}
}
[export]
def main {
someThing($(arg:B){
});
someThing($(arg:C){
});
someThing($(arg:D){ // fails to compile with error "D const is not a subclass of Base"
});
someThing($(arg:int){ // fails to compile with error "int const is not a class at all"
});
}
```
> minor bugfix for is_subclass_of type trait

- include/daScript/simulate/simulate.h
- include/daScript/simulate/simulate_fusion.h
- include/daScript/simulate/simulate_nodes.h
- src/ast/ast_simulate.cpp
- src/simulate/simulate.cpp
- src/simulate/simulate_fusion.cpp
- src/simulate/simulate_fusion_ptrfdr.cpp
```
options gen2
struct Foo {
a : int = 5
}
[export]
def main {
var foo : Foo?
let x = foo.a // used to produce EXCEPTION: dereferencing null pointer at D:\Work\daScript/examples/test/misc/hello_world.das:10:15
print("x = {x}\n")
}
```
now produces
```
EXCEPTION: dereferencing null pointer, foo is null
at D:\Work\daScript/examples/test/misc/hello_world.das:10:15
```
> proof of concept, more detailed runtime error messages

- src/builtin/module_builtin_string.cpp
```
options gen2
require strings
options intern_strings       // note
[export]
def main() {
var a = "HELLO, WORLD"
var b : string
b = a
b += "_"
debug(b, "b before =")
var c = to_lower(b)
debug(b, "b=")                /// <---------- this used to be lower case due to interning bug
debug(c, "c=")
}
```
> to_lower and to_upper now survives string interning

- src/ast/ast_generate.cpp
- src/ast/ast_infer_type.cpp
return with lockcheck prevents CMRES in class ctor, thus breaking addr(self)
> skip lockchceck on generated c-tor

- include/daScript/ast/ast_generate.h
- src/ast/ast.cpp
- src/ast/ast_generate.cpp
- src/ast/ast_infer_type.cpp
```
struct Foo
x : int
y : string
z : table<string>
def f1(foo : Foo) : lambda<() : void>
return <- @() { print("{foo}"); } // error[30124]: implicit capture by move requires unsafe, while capturing foo
def f11(foo : Foo) : lambda<() : void>
unsafe
return <- @() { print("{foo}"); } // error[30124]: can't implicitly capture constant variable foo by move
def f12(foo : Foo) : lambda<() : void>
return <- @ capture(<-foo) () { print("{foo}"); }   // error[30124]: can't capture constant variable foo by move
def f2(foo : Foo) : lambda<() : void>
return <- @ capture(:=foo) () { print("{foo}"); }   // Works fine
def f3(foo : Foo) : lambda<() : void>
var tmpFoo := foo
return <- @ capture(<-tmpFoo) () { print("{tmpFoo}"); } // Works fine
```
> lambda capture errors and bugfixes

- src/ast/ast_aot_cpp.cpp
- src/das/ast/ast_aot_cpp.das
Ignore consts in aot functions return
> fix const in aot return

- include/daScript/simulate/aot.h
- src/ast/ast_infer_type.cpp
- src/builtin/module_builtin_runtime.cpp
```
bitfield OneTwoThree {
one,
two,
three
}
[export]
def main {
var a = OneTwoThree.one
a.two = true // this is now ok
debug(a)
a.one = false // this is also ok
debug(a)
}
```
> promote to bitfield set

- src/ast/ast_typedecl.cpp
```
def test(a) {
}
[export]
def main() {
var arg1: bitfield<left;right>;
var arg2: bitfield<up;down>;
test(arg1)
test(arg2);
}
```
Code like this doesn't work, because we cache result of the searching function by hash, however we got collision, because the only difference is argNames for bitfield type, which is not counted in lookup hash computation (so, we match same function during the search)
> add argNames to hash of bitfield

- src/ast/ast_infer_type.cpp
```
options rtti
require ast
[export] def main {
unsafe {
var first : FieldDeclaration
first._type.move_new(typeinfo ast_typedecl(type<bool>)) // now ok
}
}
```
aslo
```
require strings
[export] def main {
var name = "Hello, World!"
var i = 0
unsafe(name.character_uat(i)) // now ok
}
```
> fancier lookup for invoke foo.bar(...)

- examples/test/unit_tests/div_by_zero.das
- include/daScript/ast/ast_expressions.h
- src/ast/ast_infer_type.cpp
- src/ast/ast_lint.cpp
- forbid `return` inside `try {} recover {}` blocks
- forbid usage of finally with goto outside of block
> add linter checks for jit:

- src/ast/ast_parse.cpp
```
print("options gen2=false\n")  // this is no longer detected as options gen2
```
> skip options gen2 in string

- daslib/enum_trait.das
- tests/language/enumerations.das
conversion functions
```
enum Foo {
one
two
three
}
"{Foo.one}" // enum -> string
string(Foo.one) // enum ->string, same as previous line
to_enum(type<Foo>,"one") // can panic, if enum can't be converted
to_enum(type<Foo>,"five",Foo.one) // twith the default value
```
also conversion macro
```
[string_to_enum]
enum Bar {
one
two
three
}
Bar("two") // can panic, if enum can't be converted
Bar("five", Bar.one) // with the default value
```
> Enum traits expanded

- daslib/linq.das
- daslib/linq_boost.das
- tests/linq/test_linq_fold.das
- tests/linq/test_linq_sorting.das
order without arguments now sorts by unique_key
order/distinct and distinct/order folded into order/unique aggregate
```
var seq = (
[5, 4, 4, 3, 4, 2, 1, 1, 4, 3]
.distinct()
.order()
._fold()
)
```
is the same as
```
var t7 = (
[5, 4, 4, 3, 4, 2, 1, 1, 4, 3]
.order()
.unique() // fused operation
._fold()
)
```
> unqiue - removes matching sequential elements
